FROM openjdk:21

WORKDIR /app

COPY ./build/libs/backend-0.0.1-SNAPSHOT.jar ./backend_build.jar

EXPOSE 8080

CMD ["java", "-Duser.timezone=Asia/Seoul", "-jar", "-Dspring.profiles.active=server", "backend_build.jar"]